### ISSUE TITLE
Simplify UI

### ISSUE THREAD

**Issue by peteruithoven** [arshubham/srtnr#16]
(I know you already have this as a task for MVP+1, but I can't comment in tasks)

I couldn't help myself to think about the ui for a bit. This is a rough suggestion for a simpler UI:

![frame 3](https://user-images.githubusercontent.com/523210/35773203-89f521e4-094b-11e8-8ca6-bfd3cfe203e9.png)

- I would retrieve the http / https from the given url. (this was already suggested by someone on Google+)
- I ould put the provider choice in a dropdown box because I it simplifies the ui visually and I can't imagine people changing there preference frequently? But I'm curious what you think about that. The value would need to be stored for next time. 
- The shortened field could be updated on any change in the form. I'm assuming this will usually be one change, pasting a new url. 
- The highlighted "apply" button would copy the shortened url to clipboard. This action should  probably also be executed when pressing enter. You could also forgo the buttons when you implement #15, but I feel it's quite uncommon for apps to change the clipboard without a more explicit action.

**Comment by arshubham** [comment]
@peteruithoven  How does it look now?
![screenshot from 2018-02-06 16 00 59](https://user-images.githubusercontent.com/14235191/35854688-04dd5838-0b57-11e8-9d88-04a8f05004d0.png)

>  The value would need to be stored for next time.

It is in progress

> retrieve the http / https from the given url

Done.

> This action should probably also be executed when pressing enter.

I am working on it, having some issues with it.

It also now shows a notification on successful generation and copy's to the clipboard.
If you have any more suggestions, please do suggest. I still have a lot to learn in UX design.

**Comment by peteruithoven** [comment]
Nice! That's already a lot clearer. 

>> The value would need to be stored for next time.

> It is in progress

I know you're doing this in Rust, but maybe you can somehow reuse some of how I did it:
https://github.com/peteruithoven/resizer/commit/eb118af4bc1d220d2a7714cd3b448bb51e6e4d6a

>> This action should probably also be executed when pressing enter.

> I am working on it, having some issues with it.

You'll need to enable the `can_default` on your Shorten URL button and call the `set_default ()` function on your ApplicationWindow giving it the button that it should default to. (Or at least that's how I got it to work in Vala)

**Comment by arshubham** [comment]
I have already used gschema in my vala app.  I am just waiting for some packaging issues to resolve and doing some refactoring to make the app easier to maintain and act as a template for future. It seems that meson will not be working with rust. Currently  @btkostner is working on a solution. https://github.com/btkostner/srtnr/tree/packaging . 

As for the default button, it didn't work at first. I will look into it again in a day or two.

Finally, thanks for the feedback.

**Comment by arshubham** [comment]
> This action should probably also be executed when pressing enter.

Addressed in https://github.com/arshubham/srtnr/commit/98b9366144c14449b4195c93cfe15921a1cfedd4

> The value would need to be stored for next time.

Addressed in https://github.com/arshubham/srtnr/commit/2e9fe34529c66798c17daa51ea97c4cad7a73381
